### ISSUE TITLE
Support for Google CloudBuild

### ISSUE THREAD

**Issue by phish3y** [frantjc/forge#301]
It would be nice for forge to support Google Cloud Build. To access GCP resources while running a container locally you could mount credentials into the container as such:

```yaml
 volumes:
   - ~/.config/gcloud:/root/.config/gcloud
```

Some plugins that I would like to use are:

```yaml
- id: id1
  name: gcr.io/cloud-builders/docker
```

```yaml
- id: id1
  name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
```

```yaml
- id: id1
  name: "docker/compose:1.29.2"
```

**Comment by frantjc** [comment]
I'd like to support cloudbuild as well. this release is a rough stab at satisfying your requirements: https://github.com/frantjc/forge/releases/tag/v0.15.0-alpha0

for the first example, you'd run something like

```sh
forge cloudbuild gcr.io/cloud-builders/docker -t your-tag .
```

**Comment by phish3y** [comment]
I can confirm this is working
